name: dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - ipython
  - black
  - cookiecutter
  - flake8
  - git
  - git-lfs
  - isort
  - mamba
  - nodejs
  - pre-commit
  - snakefmt
  - snakemake
  - bcftools
  - samtools
  - snakemake
  - snakemake-storage-plugin-s3
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-cluster-generic
  - plink
  - pytest
  - pytest-cov
  - pyyaml
# support for R linting utilities
  - r-base
  - r-ggplot2
  - r-tidyverse
  - r-rmarkdown
  - r-devtools
  - r-docopt
  - r-lintr
  - r-styler
  - r-usethis
  - r-knitr
  - r-sf
  - r-plotly



